#!/bin/bash
# Désinstallation Moncine — paquet YunoHost

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# SUPPRESSION DE LA CONFIG SYSTÈME
#=================================================
ynh_script_progression "Suppression de la configuration système de ${app}…"

ynh_config_remove_nginx
ynh_config_remove_phpfpm

#=================================================
# FIN
#=================================================
ynh_script_progression "Désinstallation de ${app} terminée."
