#!/bin/bash
# Restauration Moncine — paquet YunoHost

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# RESTAURATION DU CODE ET DES DONNÉES
#=================================================
ynh_script_progression "Restauration du dossier d’installation…"

ynh_restore "${install_dir}"
chown -R "${app}:www-data" "${install_dir}"

ynh_script_progression "Restauration du dossier de données…"

ynh_restore "${data_dir}"
moncine_fix_data_permissions

#=================================================
# RESTAURATION DE LA CONFIG SYSTÈME
#=================================================
ynh_script_progression "Restauration de PHP-FPM et NGINX…"

ynh_restore "/etc/php/${php_version}/fpm/pool.d/${app}.conf"
ynh_restore "/etc/nginx/conf.d/${domain}.d/${app}.conf"

#=================================================
# RECHARGEMENT DES SERVICES
#=================================================
ynh_script_progression "Rechargement de PHP-FPM et NGINX…"

ynh_systemctl --service="php${php_version}-fpm" --action=reload
ynh_systemctl --service=nginx --action=reload

#=================================================
# FIN
#=================================================
ynh_script_progression "Restauration de ${app} terminée."
